steps:
- id  : Build-Docker
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/hargapangan-scraping:$SHORT_SHA', '.']

- id  : Test
  name: 'asia.gcr.io/$PROJECT_ID/hargapangan-scraping:$SHORT_SHA'
  entrypoint : python
  args: ['test.py']

- id  : Push-Docker
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/$PROJECT_ID/hargapangan-scraping:$SHORT_SHA']

- id  : envSubst-for-deployment.yaml
  name: 'gcr.io/$PROJECT_ID/envsubst'
  env :
    - 'SHORT_SHA=$SHORT_SHA'
    - 'PROJECT_ID=$PROJECT_ID'
  args: ['deployment.yaml']

- id  : Apply-configuration
  name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'apply'
  - '-f'
  - 'deployment.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast2-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=jenkins-cd'

- id  : Deploy-to-GKE
  name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'beta'
  - 'run'
  - 'deploy'
  - 'hargapangan-scraping-test'
  - '--image'
  - 'asia.gcr.io/$PROJECT_ID/hargapangan-scraping:$SHORT_SHA'
  - '--region'
  - 'asia-southeast2-a'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
