apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scheduling-scrape
spec:
  schedule: "0 7 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scraping-hargapangan
            image: gcr.io/price-forecasting-try/scraping-hargapangan:$BUILD_NUMBER
            command: ["python", "main.py"]
          restartPolicy: OnFailure
